manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      #revision: main # This is the original that updates automatically, but will break the builds cause of compatability issues.
      revision: v0.2
      import: app/west.yml
  self:
    path: config

